fix: GHA CI status check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -64,15 +64,18 @@ jobs:
           docker compose up -d
           docker compose down
 
-  ci-check:
-    name: ci status check
+  results:
+    name: CI Status Check
     runs-on: ubuntu-latest
     needs: [ci]
     if: always()
     steps:
-      - name: Some CI failed
-        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')}}
-        run: exit 1
-      - name: All CI passed
-        if: ${{ contains(needs.*.result, 'success') || contains(needs.*.result, 'skipped') }}
-        run: exit 0
+      - name: Evaluate CI status
+        run: |
+          if contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'); then
+            echo "Some CI checks failed"
+            exit 1
+          else
+            echo "All CI checks passed"
+            exit 0
+          fi
